version: "3"

volumes:
  pgdata_test:
  conf_test:
  tnexttestm2_test:

services:
  db:
    command: postgres --log_statement=all
    restart: always
    command: postgres
    image: mdillon/postgis:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    ports:
      - "5432"

  tnexttest:
    build: ../
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: db
    volumes:
      - tnexttestm2_test:/root/.m2
      - "./scripts:/scripts"
      - "./data:/data"
      - "./conf:/app/conf"
    ports:
      - "18080:8080"
    links:
      - db

  pyresttest:
    build: ./api-tests/
    environment:
      TNAST_HOST: "tnexttest:8080"
    volumes:
      - "./api-tests:/api-tests"
      - "./scripts:/scripts"
      - "./data:/data"
    links:
      - tnexttest
      - db      

