db:
  image: mdillon/postgis
  command: postgres --log_statement=all
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  volumes:
    - pgdata:/var/lib/postgresql/data
  ports:
    - "5432:5432"

tnast:
  build: ../TNAtoolAPI-Webapp/
  volumes:
    - tnastm2:/root/.m2
    - "./scripts:/scripts"
    - "./data:/data"
    - "./conf:/app/conf"
  ports:
    - "8080:8080"
  links:
    - db

pyresttest:
  build: ./api-tests/
  environment:
    TNAST_HOST: "tnast:8080"
  volumes:
    - "./api-tests:/api-tests"
    - "./scripts:/scripts"
    - "./data:/data"
  links:
    - tnast
    - db
