version: "3"

volumes:
  pgdata:
  conf:

services:
  db:
    restart: always
    command: postgres --log_statement=all
    image: mdillon/postgis:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432"

  tnast:
    build: .
    restart: always
    volumes:
      - tnastm2:/root/.m2
      - ./data:/data
      - ./conf:/app/conf
      - ./conf/temp:/var/lib/tomcat8/temp
    ports:
      - "8080:8080"
    links:
      - db
