version: "3"

volumes:
  pgdata:
  conf:

services:
  db:
    image: mdillon/postgis:9.5
    command: postgres --log_statement=all
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432"

  tnast:
    build: .
    volumes:
      - conf:/app/conf
    ports:
      - "8080:8080"
    links:
      - db
